# The image that will be used in the deployment
image: registry.scs.community/cluster-gen/capi-jsgen:0.0.5

# Ingress related config
ingress:
  # whether to deploy an ingress resource at all
  enabled: true
  # hostname used for ingress, tls-cert (optional) and dns-entry (optional)
  hostname: capi-jsgen.moin.k8s.scs.community
  # whether to create an annotation for the creation of an dns entry via external-dns
  dnsAnnotation: true
  # whether to set a cert-manager cluster-issues, also activates tls for this ingress
  clusterIssuer: letsencrypt
  # ingressClassName for this ingress
  className: nginx